# This file was generated by GoReleaser. DO NOT EDIT.
cask "moonshine" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6c13d1563dc9eaa36431dc883cb493881f22a7ca7006c9ba1ec5edbe1be5c934"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_macOS_x86_64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
    on_arm do
      sha256 "6d52db1394c5685840953b4f6f477fca06bda67c0e36bfe6318a43e144f83b37"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_macOS_arm64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
  end

  on_linux do
    on_intel do
      sha256 "baae82b5d2e885bb9d130883b31a636469fbc5fd2c2fa0f17ae5a14e3bf6cd74"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_linux_x86_64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
    on_arm do
      sha256 "6913e26c836f8590bf86dbc6df22c9b4dd5dafe81d7c18dc7efbcd8fcaa82433"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_linux_arm64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
  end

  name "moonshine"
  desc "Moonshine CLI"
  homepage "https://pyrorhythm.dev/moonshine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moonshine"
  generate_completions_from_executable "moonshine", "completion",
    shell_parameter_format: :arg,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
