# This file was generated by GoReleaser. DO NOT EDIT.
cask "moonshine" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "54c37bacfbb05c5facc20bec22ff8c9f50ee3db6d19fba0ec3015ca573f284e7"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_macOS_x86_64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
    on_arm do
      sha256 "b2ae1fe71961b76747ef5b8c8b219ca6fd2201a43a78cfad3862cd9e63aaff60"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_macOS_arm64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
  end

  on_linux do
    on_intel do
      sha256 "de13520f06b2416306f26d2be792b7dac2fae9cdd0cd38d6303142c9781a9d38"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_linux_x86_64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
    on_arm do
      sha256 "ee15977de87bd37bbb5f7e6cc7be2400729c348c36aedf208d0cea1ea91c3d5d"
      url "https://github.com/pyrorhythm/moonshine/releases/download/v#{version}/moonshine_#{version}_linux_arm64.tar.gz",
        verified: "https://github.com/pyrorhythm/moonshine"
    end
  end

  name "moonshine"
  desc "Moonshine CLI"
  homepage "https://pyrorhythm.dev/moonshine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moonshine"
  generate_completions_from_executable "moonshine", "completion",
    shell_parameter_format: :arg,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
